---
- name: clone omarchy star blue theme
  become: true
  become_user: "{{ main_user }}"
  git: repo=https://github.com/mtnstar/omarchy-star-blue-theme.git dest=~/config/omarchy/star-blue update=yes
